# Generated by Django 2.1.3 on 2018-11-08 11:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Enter an email subject', max_length=100)),
                ('body', models.TextField(help_text='Enter the message body')),
                ('status', models.CharField(help_text='Draft, Outbox, or Sent', max_length=50)),
                ('time_sent', models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 8, 11, 30, 13, 395739))),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
