# Generated by Django 2.1.1 on 2018-11-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Enter an email subject', max_length=100)),
                ('messageText', models.TextField(help_text='Enter the message body')),
                ('messageStatus', models.CharField(help_text='Draft, Outbox, or Sent', max_length=50)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.CharField(help_text='Enter your username', max_length=50)),
                ('checkBox', models.BooleanField(default=False)),
            ],
        ),
    ]
