# Generated by Django 2.1.1 on 2018-11-30 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='time_scheduled',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('draft', 'Draft'), ('scheduled', 'Scheduled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='email',
            name='time_sent',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
