# Generated by Django 2.1.10 on 2019-07-09 03:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='contacted_selection',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('U', 'Uncontacted'), ('C1', 'Contacted <= 1'), ('C2', 'Contacted <= 2'), ('C0', 'Contacted > 0')], max_length=10),
        ),
        migrations.AlterField(
            model_name='email',
            name='primary_selection',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('P', 'Primary'), ('NP', 'Not-Primary')], max_length=4),
        ),
        migrations.AlterField(
            model_name='email',
            name='size_selection',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=5),
        ),
    ]
