# Generated by Django 2.1.1 on 2018-11-08 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='timeScheduled',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 7, 23, 15, 49, 691479)),
        ),
    ]
