# Generated by Django 2.1.1 on 2018-12-06 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20181108_1056'),
        ('emails', '0002_auto_20181129_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='companies.Company'),
            preserve_default=False,
        ),
    ]
