# Generated by Django 2.1.10 on 2019-07-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20190709_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='to_companies',
            field=models.ManyToManyField(blank=True, related_name='email_templates', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_contacts',
            field=models.ManyToManyField(blank=True, related_name='email_templates', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_industries',
            field=models.ManyToManyField(blank=True, to='companies.Industry'),
        ),
    ]
