# Generated by Django 2.1.1 on 2018-11-08 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_timescheduled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='checkBox',
            new_name='check_box',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='lastUpdate',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='messageStatus',
            new_name='message_status',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='messageText',
            new_name='message_text',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='modifiedBy',
            new_name='modified_by',
        ),
        migrations.RemoveField(
            model_name='email',
            name='timeScheduled',
        ),
        migrations.AddField(
            model_name='email',
            name='time_scheduled',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 7, 23, 43, 50, 744858)),
        ),
    ]
