# Generated by Django 2.1.2 on 2018-11-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20181108_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('scheduled', 'Scheduled')], max_length=10),
        ),
    ]
