# Generated by Django 2.1.1 on 2019-07-10 02:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20190709_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='contacted_selection',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('U', 'Uncontacted'), ('C1', 'Contacted 1x'), ('C2', 'Contacted 2x'), ('C3', 'Contacted 3x or more')], max_length=10),
        ),
    ]
