# Generated by Django 2.1.1 on 2018-12-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20181108_1056'),
        ('emails', '0003_email_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='company',
        ),
        migrations.AddField(
            model_name='email',
            name='to',
            field=models.ManyToManyField(blank=True, to='companies.Company'),
        ),
    ]
