# Generated by Django 2.2.3 on 2019-08-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_auto_20190802_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='internal_title',
            field=models.CharField(default='', help_text='Enter an internal title for this email', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(help_text='Enter an email subject', max_length=200),
        ),
    ]
