# Generated by Django 2.2.3 on 2019-08-04 01:31

from django.db import migrations
import shared.forms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_auto_20190803_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='size_selection',
            field=shared.forms.fields.MultiSelectField(blank=True, choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small'), ('U', 'Unknown')], max_length=7),
        ),
    ]
