# Generated by Django 2.2.3 on 2019-08-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20190802_0336'),
        ('emails', '0007_auto_20190804_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sent_contacts',
            field=models.ManyToManyField(blank=True, related_name='emails_sent', to='contacts.Contact'),
        ),
    ]
