# Generated by Django 2.2.3 on 2019-08-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_email_attach_packet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='time_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='time_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
