# Generated by Django 2.2.3 on 2019-08-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0011_auto_20190805_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='exclude_contacted_companies',
            field=models.BooleanField(default=False, help_text='Whether to exclude all contacts from companies who have already been contacted'),
        ),
    ]
