# Generated by Django 2.2.4 on 2019-09-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_email_exclude_contacted_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='exclude_responded_companies',
            field=models.BooleanField(default=False, help_text='Whether to exclude all contacts from companies who have been contacted and at least responded'),
        ),
    ]
