# Generated by Django 2.1.9 on 2019-06-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
