# Generated by Django 2.1.9 on 2019-06-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_warm_contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('U', 'Uncontacted'), ('C', 'Contacted')], default='U', max_length=1),
            preserve_default=False,
        ),
    ]
