# Generated by Django 2.1.1 on 2019-07-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20190702_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
