# Generated by Django 2.1.1 on 2019-07-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_primary'),
        ('contacts', '0007_auto_20190703_0804'),
    ]

    operations = [
    ]
