# Generated by Django 2.1.10 on 2019-07-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_merge_20190703_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
