# Generated by Django 2.2.3 on 2019-07-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0015_auto_20190712_0526'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sponsorships',
            field=models.ManyToManyField(blank=True, related_name='organizer_contacts', to='hackathons.Sponsorship'),
        ),
    ]
