# Generated by Django 2.1.3 on 2018-11-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='perks',
            field=models.ManyToManyField(blank=True, to='hackathons.Perk'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='tiers',
            field=models.ManyToManyField(blank=True, to='hackathons.Tier'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='perks',
            field=models.ManyToManyField(blank=True, to='hackathons.Perk'),
        ),
    ]
