# Generated by Django 2.1.2 on 2018-12-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Recieved')], max_length=12),
        ),
    ]
