# Generated by Django 2.1.3 on 2018-12-04 19:59



from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_auto_20181128_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('uncontacted', 'Uncontacted'), ('contacted', 'Contacted'), ('donated', 'Donated')], max_length=12),
        ),
    ]