# Generated by Django 2.1.1 on 2019-06-30 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_auto_20181206_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='tiers',
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='tiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathons.Tier'),
        ),
    ]
