# Generated by Django 2.1.2 on 2018-12-05 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_auto_20181204_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
