# Generated by Django 2.1.1 on 2019-06-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_auto_20190630_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='tiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorships', to='hackathons.Tier'),
        ),
    ]
