# Generated by Django 2.1.4 on 2018-12-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0004_auto_20181205_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Waiting')], max_length=12),
        ),
    ]
