# Generated by Django 2.1.1 on 2019-07-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0005_auto_20190630_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
