# Generated by Django 2.1.9 on 2019-07-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0007_auto_20190702_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='role',
            field=models.CharField(choices=[('no_role', 'None'), ('primary', 'Primary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('uncontacted', 'Uncontacted'), ('contacted', 'Contacted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('contacted', 'Contacted'), ('responded', 'Responded'), ('confirmed', 'Confirmed'), ('denied', 'Denied'), ('ghosted', 'Ghosted'), ('paid', 'Paid')], default='preparing', max_length=20),
        ),
    ]
