# Generated by Django 2.1.9 on 2019-07-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0009_auto_20190702_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='contribution',
            field=models.IntegerField(blank=True),
        ),
    ]
