# Generated by Django 2.1.9 on 2019-07-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20190702_0527'),
        ('contacts', '0006_auto_20190702_0527'),
        ('hackathons', '0011_auto_20190702_0510'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('sponsorship', 'contact')},
        ),
        migrations.AlterUniqueTogether(
            name='sponsorship',
            unique_together={('hackathon', 'company')},
        ),
    ]
