# Generated by Django 2.1.9 on 2019-07-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0012_auto_20190702_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('responded', 'Responded')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('responded', 'Responded'), ('confirmed', 'Confirmed'), ('denied', 'Denied'), ('ghosted', 'Ghosted'), ('paid', 'Paid')], default='contacted', max_length=20),
        ),
    ]
