# Generated by Django 2.1.9 on 2019-07-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0013_auto_20190702_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='times_contacted',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('ghosted', 'Ghosted'), ('responded', 'Responded')], default='contacted', max_length=20),
        ),
    ]
