# Generated by Django 2.1.1 on 2018-11-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='enter a company name (e.g. "Amazon")', max_length=140)),
                ('donated', models.IntegerField()),
                ('industry', models.IntegerField(choices=[(0, 'Web'), (4, 'Data'), (1, 'ML'), (2, 'Software'), (3, 'Systems')], default=0)),
                ('status', models.CharField(choices=[('U', 'Uncontacted'), ('C', 'Contacted'), ('D', 'Donated')], max_length=1)),
                ('size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=1)),
                ('updated', models.DateField()),
                ('contact', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
