# Generated by Django 2.1.3 on 2018-12-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20181108_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
