# Generated by Django 2.1.9 on 2019-07-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='donated',
        ),
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
    ]
