# Generated by Django 2.1.1 on 2019-07-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20190702_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_exclude',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
