# Generated by Django 2.1.10 on 2019-07-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_email_exclude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ('name',)},
        ),
    ]
