# Generated by Django 2.1.10 on 2019-07-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20190712_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(blank=True, to='companies.Industry'),
        ),
    ]
