# Generated by Django 2.2.3 on 2019-08-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20190802_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('green', 'green'), ('purple', 'purple'), ('orange', 'orange'), ('yellow', 'yellow'), ('red', 'red'), ('brown', 'brown'), ('pink', 'pink')], max_length=10),
        ),
    ]
